package com.example.quiz3.web.controller;


import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
   /* // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    public MainController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @PostMapping(path="/add/{name}/{password}/{email}") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam(value = "name", required = false) String name,
                                            @RequestParam(value = "password", required = false)  String password,
                                            @RequestParam(value = "email", required = false)  String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        users n = new users(name, password, email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<users> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }*/
}